### ISSUE TITLE
Position on the left bottom

### ISSUE THREAD

**Issue by pedrovalmor** [lejsue/symbols-navigator#32]
Hello, 
I would like to use it in the left / bottom position (under project tab) when I open Atom. 
In the config of 'Position' it has only left/right options. 
Someone know how to do this please?
Thank you in advance.

**Comment by lejsue** [comment]
Thanks for using this package, I should have some times next week. Let me figure out how to add this feature.

**Comment by pedrovalmor** [comment]
thank you! I understand a bit JS, so, if you want some help just guide me ;)

**Comment by lejsue** [comment]
Hi, 
I tried to add serialize and deserialize function this week, and have one good news and one bad news. The good one is that it works, I can drag the Symbols tab to the left bottom position, and after reopen ATOM, it's still there. And the bad news is that sometimes ATOM will crash, since it produces two Project tabs. I'm still digging out the root cause.
